name: CI

on:
  push:
    branches: ["master"]

env: 
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
          cmake --build . --config ${{env.BUILD_TYPE}}
          ctest -C ${{env.BUILD_TYPE}}
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 16
          # you can set branches for semantic-release above v16.
          branches: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

